# Generated by Django 2.1.7 on 2020-07-13 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20200713_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='datePayment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='dateTendered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
