# Generated by Django 2.1.7 on 2020-07-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_payment_interestrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='overPayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
