# Generated by Django 2.1.7 on 2020-07-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_payment_amortizationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='interestPayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
