# Generated by Django 2.1.7 on 2020-07-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_auto_20200729_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='daysAdvanced',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='daysExceed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
