# Generated by Django 2.1.7 on 2020-08-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_payment_ispaymentextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='exemptInterest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='exemptPenalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
