# Generated by Django 2.1.7 on 2020-08-16 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_auto_20200816_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='exemptInterest',
            new_name='exemptAdditionalInterest',
        ),
    ]
