# Generated by Django 2.1.7 on 2020-09-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_check_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='warehousingBatchNo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
