# Generated by Django 2.1.7 on 2020-09-11 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_auto_20200910_0158'),
        ('users', '0002_auto_20200303_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installedApps', models.ManyToManyField(blank=True, to='settings.AppName')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appAccess', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
