# Generated by Django 2.1.7 on 2020-06-05 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('committees', '0001_initial'),
        ('processes', '0004_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isDefault', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outputCreatedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='step',
            name='committee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='steptCommittes', to='committees.Committee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stepStatuses', to='processes.Statuses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='output',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='processes.Step'),
        ),
    ]
