# Generated by Django 2.1.7 on 2020-06-05 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0006_auto_20200605_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='nextStep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nextStepOutputs', to='processes.Step'),
            preserve_default=False,
        ),
    ]
