# Generated by Django 2.1.7 on 2020-06-05 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0007_output_nextstep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='oder',
            new_name='order',
        ),
    ]
