# Generated by Django 2.1.7 on 2020-06-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0001_initial'),
        ('processes', '0008_auto_20200605_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='position',
            field=models.ManyToManyField(to='committees.Position'),
        ),
    ]
