# Generated by Django 2.1.7 on 2020-06-09 15:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processes', '0010_auto_20200609_1548'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requirements',
            new_name='StepRequirement',
        ),
        migrations.RenameModel(
            old_name='Attachment',
            new_name='StepRequirementAttachment',
        ),
    ]
