# Generated by Django 2.1.7 on 2020-06-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0011_auto_20200609_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrequirement',
            name='isAttachementRequired',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='steprequirement',
            name='isAttachementRequired',
            field=models.BooleanField(default=True),
        ),
    ]
