# Generated by Django 2.1.7 on 2020-06-09 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0012_auto_20200609_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steprequirement',
            name='isDefault',
        ),
        migrations.RemoveField(
            model_name='steprequirementattachment',
            name='isDefault',
        ),
    ]
