# Generated by Django 2.1.7 on 2020-06-09 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0013_auto_20200609_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steprequirementattachment',
            name='step',
        ),
        migrations.AddField(
            model_name='steprequirementattachment',
            name='stepRequirement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stepRequirementAttachments', to='processes.StepRequirement'),
            preserve_default=False,
        ),
    ]
