# Generated by Django 2.1.7 on 2020-06-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0014_auto_20200609_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steprequirementattachment',
            old_name='file_name',
            new_name='fileName',
        ),
    ]
