# Generated by Django 2.1.7 on 2020-06-10 09:57

from django.db import migrations, models
import processes.models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0015_auto_20200609_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='steprequirementattachment',
            name='fileAttachment',
            field=models.FileField(blank=True, null=True, upload_to=processes.models.attachment_directory_path),
        ),
    ]
