# Generated by Django 2.1.7 on 2020-06-16 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documentmovement_output'),
        ('processes', '0016_steprequirementattachment_fileattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='steprequirementattachment',
            name='document',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, related_name='documentStepRequirementAttachments', to='documents.Document'),
            preserve_default=False,
        ),
    ]
