# Generated by Django 2.1.7 on 2020-06-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0017_steprequirementattachment_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='subprocess',
            name='relatedProcesses',
            field=models.ManyToManyField(to='processes.SubProcess'),
        ),
    ]
