# Generated by Django 2.1.7 on 2020-06-22 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0019_auto_20200622_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statuses',
            name='code',
        ),
    ]
