# Generated by Django 2.1.7 on 2020-06-22 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0020_remove_statuses_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='nextStep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nextStepOutputs', to='processes.Step'),
        ),
    ]
