# Generated by Django 2.1.7 on 2020-07-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0022_processrequirementattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processrequirement',
            name='code',
        ),
    ]
