# Generated by Django 2.1.7 on 2020-07-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0007_auto_20200709_1127'),
        ('processes', '0025_auto_20200729_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='position',
        ),
        migrations.AddField(
            model_name='step',
            name='positions',
            field=models.ManyToManyField(blank=True, to='committees.Position'),
        ),
    ]
