# Generated by Django 2.1.7 on 2020-07-30 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0008_auto_20200730_0614'),
        ('processes', '0026_auto_20200729_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrequirementattachment',
            name='committee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='processRequirementAttachments', to='committees.Committee'),
            preserve_default=False,
        ),
    ]
