# Generated by Django 2.1.7 on 2020-05-01 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0002_gendertype_createdby'),
    ]

    operations = [
        migrations.CreateModel(
            name='CooperativeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooperativeTypeCreatedBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cooperative Type (System Essential)',
                'verbose_name_plural': 'Cooperative Types (System Essential)',
            },
        ),
        migrations.RenameField(
            model_name='gendertype',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='gendertype',
            name='dateUpdated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gendertype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
