# Generated by Django 2.1.7 on 2020-09-03 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0003_auto_20200501_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('iconAsHTML', models.TextField(blank=True, null=True)),
                ('navDirectory', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appNameCreatedBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'App Name (System Essential)',
                'verbose_name_plural': 'App Names (System Essential)',
            },
        ),
    ]
