# Generated by Django 2.1.7 on 2020-09-09 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0004_appname'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addressCreatedBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address Type (System Essential - CIC)',
                'verbose_name_plural': 'Address Types (System Essential - CIC)',
            },
        ),
        migrations.CreateModel(
            name='CivilStatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='civilStatusTypeCreatedBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gender Type (System Essential - CIC)',
                'verbose_name_plural': 'Gender Types (System Essential - CIC)',
            },
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactTypeCreatedBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Type (System Essential - CIC)',
                'verbose_name_plural': 'Contact Types (System Essential - CIC)',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countryCreatedBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Country (System Essential - CIC)',
                'verbose_name_plural': 'Countries (System Essential - CIC)',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currencyCreatedBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Currency Type (System Essential - CIC)',
                'verbose_name_plural': 'Currency Types (System Essential - CIC)',
            },
        ),
        migrations.CreateModel(
            name='FirmSizeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmSizeTypeCreatedBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Firm Size Type (System Essential - CIC)',
                'verbose_name_plural': 'Firm Size Types (System Essential - CIC)',
            },
        ),
        migrations.CreateModel(
            name='HouseOwnerLesseeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='houseOwnerLesseeCreatedBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'House Owner Lessee Type (System Essential - CIC)',
                'verbose_name_plural': 'House Owner Lessee Types (System Essential - CIC)',
            },
        ),
        migrations.CreateModel(
            name='IdentificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identificationTypeCreatedBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identification Type (System Essential - CIC)',
                'verbose_name_plural': 'Identification Types (System Essential - CIC)',
            },
        ),
        migrations.CreateModel(
            name='IDType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idCreatedBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ID Type (System Essential - CIC)',
                'verbose_name_plural': 'ID Types (System Essential - CIC)',
            },
        ),
        migrations.CreateModel(
            name='IncomePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomePeriodCreatedBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Income Period Type (System Essential - CIC)',
                'verbose_name_plural': 'Income Period Types (System Essential - CIC)',
            },
        ),
        migrations.CreateModel(
            name='LegalFormType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legalFormTypeCreatedBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legal Form Type (System Essential - CIC)',
                'verbose_name_plural': 'Legal Form Types (System Essential - CIC)',
            },
        ),
        migrations.CreateModel(
            name='OccupationStatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupationStatusTypeCreatedBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Occupation Status Type (System Essential - CIC)',
                'verbose_name_plural': 'Occupation Status Types (System Essential - CIC)',
            },
        ),
        migrations.CreateModel(
            name='PSIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psicCreatedBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PSIC Type (System Essential - CIC)',
                'verbose_name_plural': 'PSIC Types (System Essential - CIC)',
            },
        ),
        migrations.CreateModel(
            name='PSOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psocCreatedBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PSOC Type (System Essential - CIC)',
                'verbose_name_plural': 'PSOC Types (System Essential - CIC)',
            },
        ),
        migrations.CreateModel(
            name='TitleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titleTypeCreatedBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Title Type (System Essential - CIC)',
                'verbose_name_plural': 'Title Types (System Essential - CIC)',
            },
        ),
        migrations.AlterModelOptions(
            name='gendertype',
            options={'verbose_name': 'Gender Type (System Essential - CIC)', 'verbose_name_plural': 'Gender Types (System Essential - CIC)'},
        ),
        migrations.RenameField(
            model_name='gendertype',
            old_name='name',
            new_name='value',
        ),
    ]
