# Generated by Django 2.1.7 on 2020-09-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_auto_20200909_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='civilstatustype',
            options={'verbose_name': 'Civil Status Type (System Essential - CIC)', 'verbose_name_plural': 'Civil Status Types (System Essential - CIC)'},
        ),
    ]
