# Generated by Django 2.1.7 on 2020-06-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
