# Generated by Django 2.1.7 on 2020-06-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0003_note_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
