# Generated by Django 2.1.7 on 2020-07-09 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('committees', '0004_note_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committeeUserAccount', to=settings.AUTH_USER_MODEL),
        ),
    ]
