# Generated by Django 2.1.7 on 2020-07-09 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('committees', '0005_committee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committeeCreatedBY', to=settings.AUTH_USER_MODEL),
        ),
    ]
