# Generated by Django 2.1.7 on 2020-06-02 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentmovement',
            old_name='Document',
            new_name='document',
        ),
    ]
