# Generated by Django 2.1.7 on 2020-06-05 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0008_auto_20200605_1434'),
        ('documents', '0003_document_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmovement',
            name='step',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stepDocumentMovements', to='processes.Step'),
            preserve_default=False,
        ),
    ]
