# Generated by Django 2.1.7 on 2020-06-22 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documentmovement_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='borrowers.Borrower'),
        ),
        migrations.AlterField(
            model_name='document',
            name='documentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentTypeDocuments', to='documents.DocumentType'),
        ),
    ]
