# Generated by Django 2.1.7 on 2020-06-29 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_auto_20200629_1120'),
        ('documents', '0006_auto_20200622_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='loan',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='loans.Loan'),
            preserve_default=False,
        ),
    ]
