# Generated by Django 2.1.7 on 2020-07-01 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='parentDocument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childDocuments', to='documents.Document'),
        ),
    ]
