# Generated by Django 2.1.7 on 2020-07-09 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20200701_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loanDocuments', to='loans.Loan'),
        ),
    ]
