# Generated by Django 2.1.7 on 2020-07-09 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_auto_20200709_1527'),
        ('documents', '0010_auto_20200709_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='creditLine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditLineDocuments', to='loans.CreditLine'),
        ),
    ]
