# Generated by Django 2.1.7 on 2020-07-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_document_creditline'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dateApproved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
