from django.contrib import admin
from .models import *

admin.site.register(Branch)
admin.site.register(Business)
admin.site.register(Individual)
admin.site.register(Family)
admin.site.register(Address)
admin.site.register(Identification)
admin.site.register(ID)
admin.site.register(Contact)
admin.site.register(Employment)
admin.site.register(SoleTrader)
admin.site.register(ContactPerson)
admin.site.register(Background)
admin.site.register(Director)
admin.site.register(StandingCommittee)
admin.site.register(Grant)
admin.site.register(Borrower)
admin.site.register(BorrowerAttachment)
