# Generated by Django 2.1.7 on 2020-05-14 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowers', '0006_auto_20200514_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanName', models.CharField(blank=True, max_length=255, null=True)),
                ('loanAmount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, max_length=256, null=True)),
                ('borrower', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loanBorrower', to='borrowers.Borrower')),
            ],
        ),
    ]
