# Generated by Django 2.1.7 on 2020-06-29 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_auto_20200629_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='loanStatuses', to='loans.Status'),
            preserve_default=False,
        ),
    ]
