# Generated by Django 2.1.7 on 2020-06-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interestRate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
