# Generated by Django 2.1.7 on 2020-06-29 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_auto_20200629_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='loans.Term'),
        ),
    ]
