# Generated by Django 2.1.7 on 2020-07-01 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_loan_loanprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanprogram',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loanProgram',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='programLoans', to='loans.LoanProgram'),
            preserve_default=False,
        ),
    ]
