# Generated by Django 2.1.7 on 2020-07-09 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrowers', '0010_borrowerattachment'),
        ('loans', '0011_loanprogram_creditlineamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditLines', to='borrowers.Borrower')),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loanCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('loanProgram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programCreditLines', to='loans.LoanProgram')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditLineStatuses', to='loans.Status')),
            ],
        ),
        migrations.AlterField(
            model_name='loan',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditLineCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
