# Generated by Django 2.1.7 on 2020-07-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0013_auto_20200709_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditline',
            name='dateApproved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditline',
            name='dateExpired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
