# Generated by Django 2.1.7 on 2020-07-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0014_auto_20200709_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='dateApproved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='dateReleased',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
