# Generated by Django 2.1.7 on 2020-07-09 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0015_auto_20200709_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amortization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField(default=0)),
                ('dateApproved', models.DateTimeField(blank=True, null=True)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principalBalance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amortizationCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amortizations', to='loans.Loan')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortizationStatuses', to='loans.Status')),
            ],
        ),
    ]
