# Generated by Django 2.1.7 on 2020-07-09 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0016_amortization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amortization',
            old_name='dateApproved',
            new_name='schedule',
        ),
    ]
