# Generated by Django 2.1.7 on 2020-07-13 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0018_loan_creditline'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmortizationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField(default=0)),
                ('schedule', models.DateTimeField(blank=True, null=True)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('principalBalance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='amortization',
            name='days',
        ),
        migrations.RemoveField(
            model_name='amortization',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='amortization',
            name='principal',
        ),
        migrations.RemoveField(
            model_name='amortization',
            name='principalBalance',
        ),
        migrations.RemoveField(
            model_name='amortization',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='amortization',
            name='total',
        ),
        migrations.RemoveField(
            model_name='amortization',
            name='vat',
        ),
        migrations.AddField(
            model_name='amortizationitem',
            name='amortization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amortizationItems', to='loans.Amortization'),
        ),
        migrations.AddField(
            model_name='amortizationitem',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortizationItemStatuses', to='loans.Status'),
        ),
    ]
