# Generated by Django 2.1.7 on 2020-07-13 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0020_auto_20200713_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='amortization',
            name='amortizationStatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='amortizationStatusesAmortizations', to='loans.AmortizationStatus'),
            preserve_default=False,
        ),
    ]
