# Generated by Django 2.1.7 on 2020-07-14 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0021_amortization_amortizationstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amortizationitem',
            name='status',
        ),
        migrations.AddField(
            model_name='amortizationitem',
            name='amortizationStatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='amortizationItemStatuses', to='loans.AmortizationStatus'),
            preserve_default=False,
        ),
    ]
