# Generated by Django 2.1.7 on 2020-07-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0022_auto_20200714_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='amortization',
            name='dateReleased',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
