# Generated by Django 2.1.7 on 2020-07-22 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0024_interestrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interestRate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='loans.InterestRate'),
        ),
    ]
