# Generated by Django 2.1.7 on 2020-07-22 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0025_auto_20200722_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditline',
            name='interestRate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditLines', to='loans.InterestRate'),
        ),
    ]
