# Generated by Django 2.1.7 on 2020-07-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0026_auto_20200722_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='dateReleased',
            field=models.DateField(blank=True, null=True),
        ),
    ]
