# Generated by Django 2.1.7 on 2020-07-28 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0028_auto_20200727_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanprogram',
            name='creditLineAmount',
        ),
    ]
