# Generated by Django 2.1.7 on 2020-07-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0029_remove_loanprogram_creditlineamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanprogram',
            name='code',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
