# Generated by Django 2.1.7 on 2020-07-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0031_auto_20200728_0708'),
    ]

    operations = [
         
    ]
