# Generated by Django 2.1.7 on 2020-07-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0033_loan_loanstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='amortizationitem',
            name='additionalInterest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='amortizationitem',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
