# Generated by Django 2.1.7 on 2020-08-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0035_auto_20200729_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amortizationitem',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='amortizationitem',
            name='schedule',
            field=models.DateField(blank=True, null=True),
        ),
    ]
