# Generated by Django 2.1.7 on 2020-08-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0036_auto_20200817_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='amortization',
            name='cycle',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='amortization',
            name='schedules',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
