# Generated by Django 2.1.7 on 2020-08-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0038_amortization_termsdays'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amortization',
            old_name='termsDays',
            new_name='termDays',
        ),
    ]
