# Generated by Django 2.1.7 on 2020-08-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0039_auto_20200817_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='isRestructured',
            field=models.BooleanField(default=False),
        ),
    ]
