# Generated by Django 2.1.7 on 2020-09-15 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0040_loan_isrestructured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='paymentPeriod',
        ),
        migrations.AddField(
            model_name='term',
            name='interestPaymentPeriod',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interestPaymentPeriod', to='loans.PaymentPeriod'),
        ),
        migrations.AddField(
            model_name='term',
            name='principalPaymentPeriod',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principalPaymentPeriod', to='loans.PaymentPeriod'),
        ),
    ]
