# Generated by Django 2.1.7 on 2020-09-15 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0042_auto_20200915_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='interestPaymentPeriod',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interestPaymentPeriod', to='loans.PaymentPeriod'),
        ),
        migrations.AlterField(
            model_name='term',
            name='principalPaymentPeriod',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principalPaymentPeriod', to='loans.PaymentPeriod'),
        ),
    ]
