# Generated by Django 2.1.7 on 2020-09-17 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0044_auto_20200915_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='days',
            field=models.PositiveIntegerField(default=720, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)]),
        ),
    ]
