# Generated by Django 2.1.7 on 2020-09-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0045_auto_20200917_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='amortizationitem',
            name='accruedInterest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
