# Generated by Django 2.1.7 on 2020-09-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0046_amortizationitem_accruedinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='amortizationitem',
            name='deductAccruedInterest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
