# Generated by Django 2.1.7 on 2020-10-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0047_amortizationitem_deductaccruedinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amortizationitem',
            name='accruedInterest',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='amortizationitem',
            name='deductAccruedInterest',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='amortizationitem',
            name='interest',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='amortizationitem',
            name='principal',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
