# Generated by Django 2.1.7 on 2020-05-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0002_auto_20200501_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cooperative',
            old_name='cdaRegistrateionDate',
            new_name='cdaRegistrationDate',
        ),
    ]
