# Generated by Django 2.1.7 on 2020-05-13 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0004_auto_20200513_0634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='yearsInCooop',
            new_name='yearsInCoop',
        ),
    ]
