# Generated by Django 2.1.7 on 2020-05-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0005_auto_20200513_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standingcommittee',
            old_name='yearsInCooop',
            new_name='yearsInCoop',
        ),
    ]
