# Generated by Django 2.1.7 on 2020-05-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0006_auto_20200514_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
