# Generated by Django 2.1.7 on 2020-05-26 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0008_auto_20200526_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='clientSince',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='cdaRegistrationDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
