# Generated by Django 2.1.7 on 2020-06-23 12:04

import borrowers.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrowers', '0009_auto_20200526_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=255)),
                ('fileAttachment', models.FileField(blank=True, null=True, upload_to=borrowers.models.attachment_directory_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowerAttachments', to='borrowers.Borrower')),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowerAttachmentCreatedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
