# Generated by Django 2.1.7 on 2020-09-09 17:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_auto_20200910_0158'),
        ('borrowers', '0010_borrowerattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetNo', models.CharField(blank=True, max_length=255, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=255, null=True)),
                ('subdivision', models.CharField(blank=True, max_length=255, null=True)),
                ('barangay', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('occupiedSince', models.DateField(null=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('addressType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualAddress', to='settings.AddressType')),
            ],
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icRiskRating', models.CharField(blank=True, max_length=255, null=True)),
                ('cdaRegistrationDate', models.DateField(default=datetime.date.today)),
                ('initialMembershipSize', models.IntegerField()),
                ('membershipSize', models.IntegerField()),
                ('paidUpCapitalInitial', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('noOfCooperators', models.IntegerField()),
                ('coconutFarmers', models.IntegerField()),
                ('authorized', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('fullyPaidSharesNo', models.IntegerField()),
                ('bookValue', models.IntegerField()),
                ('parValue', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('paidUp', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('fullyPaidPercent', models.IntegerField()),
                ('initialPaidUpShare', models.IntegerField()),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeName', models.CharField(blank=True, max_length=255, null=True)),
                ('officiealRegisteredTradeName', models.CharField(blank=True, max_length=255, null=True)),
                ('resident', models.BooleanField(default=True)),
                ('termOfExistence', models.DateField(null=True)),
                ('registrationDate', models.DateField(null=True)),
                ('numberOfEmployees', models.IntegerField()),
                ('grossIncome', models.IntegerField()),
                ('netTaxableIncome', models.IntegerField()),
                ('monthlyExpenses', models.IntegerField()),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businessCurrency', to='settings.Currency')),
                ('firmSize', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businessFirmSize', to='settings.Currency')),
                ('legalForm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businessLegalForm', to='settings.LegalFormType')),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businessNationality', to='settings.Country')),
                ('psic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businessPSIC', to='settings.PSIC')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businessContact', to='borrowers.Business')),
                ('contactType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualContact', to='settings.ContactType')),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeName', models.CharField(blank=True, max_length=255, null=True)),
                ('tin', models.CharField(blank=True, max_length=255, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('grossIncome', models.IntegerField()),
                ('dateHiredFrom', models.DateField(null=True)),
                ('dateHiredTo', models.DateField(null=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualEmploymentCurrency', to='settings.Currency')),
                ('incomeIndicator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualEmploymentIncomeIndicator', to='settings.IncomePeriod')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spouseFirstName', models.CharField(blank=True, max_length=255, null=True)),
                ('spouseLastName', models.CharField(blank=True, max_length=255, null=True)),
                ('spouseMiddleName', models.CharField(blank=True, max_length=255, null=True)),
                ('motherMaidenFirstName', models.CharField(blank=True, max_length=255, null=True)),
                ('motherMaidenLastName', models.CharField(blank=True, max_length=255, null=True)),
                ('motherMaidenMiddleName', models.CharField(blank=True, max_length=255, null=True)),
                ('fatherFirstName', models.CharField(blank=True, max_length=255, null=True)),
                ('fatherLastName', models.CharField(blank=True, max_length=255, null=True)),
                ('fatherMiddleName', models.CharField(blank=True, max_length=255, null=True)),
                ('fatherSuffix', models.CharField(blank=True, max_length=255, null=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('idIssueDate', models.DateField(null=True)),
                ('idExpiryDate', models.DateField(null=True)),
                ('isIssuedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('idIssueCountry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualIDCountry', to='settings.Country')),
                ('idType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualID', to='settings.IDType')),
            ],
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificationNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businessIdentification', to='borrowers.Business')),
                ('identificationType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualIdentificationType', to='settings.IdentificationType')),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('middlename', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('suffix', models.CharField(blank=True, max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('previousLastName', models.CharField(blank=True, max_length=255, null=True)),
                ('dateOfBirth', models.DateField(null=True)),
                ('placeOfBirth', models.CharField(blank=True, max_length=255, null=True)),
                ('resident', models.BooleanField(default=True)),
                ('numberOfDependents', models.IntegerField()),
                ('carsOwned', models.IntegerField()),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('countryOfBirth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualCountryOfBirth', to='settings.Country')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualGender', to='settings.GenderType')),
                ('maritalStatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualCivilStatus', to='settings.CivilStatusType')),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualNationality', to='settings.Country')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualTitle', to='settings.TitleType')),
            ],
        ),
        migrations.CreateModel(
            name='SoleTrader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeName', models.CharField(blank=True, max_length=255, null=True)),
                ('streetNo', models.CharField(blank=True, max_length=255, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=255, null=True)),
                ('subdivision', models.CharField(blank=True, max_length=255, null=True)),
                ('barangay', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('occupiedSince', models.DateField(null=True)),
                ('dateUpdated', models.DateTimeField(auto_now_add=True)),
                ('addressType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualSoleTraderAddress', to='settings.AddressType')),
                ('individual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individualSoleTrader', to='borrowers.Individual')),
                ('ownerLessee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualSoleTraderOwnerLessee', to='settings.HouseOwnerLesseeType')),
            ],
        ),
        migrations.RemoveField(
            model_name='cooperative',
            name='cooperativeType',
        ),
        migrations.RemoveField(
            model_name='cooperative',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='contactPerson',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='cooperative',
        ),
        migrations.RemoveField(
            model_name='director',
            name='cooperative',
        ),
        migrations.RemoveField(
            model_name='grant',
            name='cooperative',
        ),
        migrations.RemoveField(
            model_name='standingcommittee',
            name='cooperative',
        ),
        migrations.AddField(
            model_name='borrower',
            name='branchCode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='providerCode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='providerSubjectNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='recordType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='subjectReferenceDate',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Cooperative',
        ),
        migrations.AddField(
            model_name='identification',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualIdentification', to='borrowers.Individual'),
        ),
        migrations.AddField(
            model_name='id',
            name='individual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idIndividual', to='borrowers.Individual'),
        ),
        migrations.AddField(
            model_name='family',
            name='individual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individualFamily', to='borrowers.Individual'),
        ),
        migrations.AddField(
            model_name='employment',
            name='individual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individualEmployment', to='borrowers.Individual'),
        ),
        migrations.AddField(
            model_name='employment',
            name='occupation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualEmploymentPSOC', to='settings.PSOC'),
        ),
        migrations.AddField(
            model_name='employment',
            name='occupationStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualEmploymentOccupationStatus', to='settings.OccupationStatusType'),
        ),
        migrations.AddField(
            model_name='employment',
            name='psic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualEmploymentPSIC', to='settings.PSIC'),
        ),
        migrations.AddField(
            model_name='contact',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualContact', to='borrowers.Individual'),
        ),
        migrations.AddField(
            model_name='background',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businessBackground', to='borrowers.Business'),
        ),
        migrations.AddField(
            model_name='address',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businessAddress', to='borrowers.Business'),
        ),
        migrations.AddField(
            model_name='address',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualAddress', to='borrowers.Individual'),
        ),
        migrations.AddField(
            model_name='address',
            name='ownerLessee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualAddressOwnerLessee', to='settings.HouseOwnerLesseeType'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='business',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowerBusiness', to='borrowers.Business'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='individual',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowerIndividual', to='borrowers.Individual'),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businessContactPerson', to='borrowers.Business'),
        ),
        migrations.AddField(
            model_name='director',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businessDirectors', to='borrowers.Business'),
        ),
        migrations.AddField(
            model_name='grant',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businessGrants', to='borrowers.Business'),
        ),
        migrations.AddField(
            model_name='standingcommittee',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businessStandingCommittees', to='borrowers.Business'),
        ),
    ]
