# Generated by Django 2.1.7 on 2020-09-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0011_auto_20200910_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='clientSince',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='subjectReferenceDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
