# Generated by Django 2.1.7 on 2020-09-09 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0012_auto_20200910_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addressType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualAddress', to='settings.AddressType'),
        ),
        migrations.AlterField(
            model_name='address',
            name='occupiedSince',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='ownerLessee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualAddressOwnerLessee', to='settings.HouseOwnerLesseeType'),
        ),
        migrations.AlterField(
            model_name='background',
            name='bookValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='coconutFarmers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='fullyPaidPercent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='fullyPaidSharesNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='initialMembershipSize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='initialPaidUpShare',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='membershipSize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='noOfCooperators',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowerCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='business',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businessCurrency', to='settings.Currency'),
        ),
        migrations.AlterField(
            model_name='business',
            name='firmSize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businessFirmSize', to='settings.Currency'),
        ),
        migrations.AlterField(
            model_name='business',
            name='grossIncome',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='legalForm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businessLegalForm', to='settings.LegalFormType'),
        ),
        migrations.AlterField(
            model_name='business',
            name='monthlyExpenses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businessNationality', to='settings.Country'),
        ),
        migrations.AlterField(
            model_name='business',
            name='netTaxableIncome',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='numberOfEmployees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='psic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businessPSIC', to='settings.PSIC'),
        ),
        migrations.AlterField(
            model_name='business',
            name='registrationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contactType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualContact', to='settings.ContactType'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactPersonCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='director',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directorCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='director',
            name='yearsInCoop',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualEmploymentCurrency', to='settings.Currency'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='dateHiredFrom',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='dateHiredTo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='grossIncome',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='incomeIndicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualEmploymentIncomeIndicator', to='settings.IncomePeriod'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individualEmployment', to='borrowers.Individual'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualEmploymentPSOC', to='settings.PSOC'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='occupationStatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualEmploymentOccupationStatus', to='settings.OccupationStatusType'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='psic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualEmploymentPSIC', to='settings.PSIC'),
        ),
        migrations.AlterField(
            model_name='family',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individualFamily', to='borrowers.Individual'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grantCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grant',
            name='projectType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='id',
            name='idExpiryDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='id',
            name='idIssueCountry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualIDCountry', to='settings.Country'),
        ),
        migrations.AlterField(
            model_name='id',
            name='idIssueDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='id',
            name='idType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualID', to='settings.IDType'),
        ),
        migrations.AlterField(
            model_name='id',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idIndividual', to='borrowers.Individual'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='carsOwned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='countryOfBirth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualCountryOfBirth', to='settings.Country'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualGender', to='settings.GenderType'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualNationality', to='settings.Country'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='numberOfDependents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualTitle', to='settings.TitleType'),
        ),
        migrations.AlterField(
            model_name='soletrader',
            name='addressType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualSoleTraderAddress', to='settings.AddressType'),
        ),
        migrations.AlterField(
            model_name='soletrader',
            name='individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individualSoleTrader', to='borrowers.Individual'),
        ),
        migrations.AlterField(
            model_name='soletrader',
            name='occupiedSince',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soletrader',
            name='ownerLessee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individualSoleTraderOwnerLessee', to='settings.HouseOwnerLesseeType'),
        ),
        migrations.AlterField(
            model_name='standingcommittee',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standingcommittee',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standingCommitteeCreatedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='standingcommittee',
            name='yearsInCoop',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
