# Generated by Django 2.1.7 on 2020-09-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0015_auto_20200910_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowerattachment',
            name='fileName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='standingcommittee',
            name='educationalAttainment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='standingcommittee',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
