# Generated by Django 2.1.7 on 2020-09-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0016_auto_20200910_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='officiealRegisteredTradeName',
            new_name='officialRegisteredTradeName',
        ),
        migrations.AlterField(
            model_name='business',
            name='termOfExistence',
            field=models.DateField(blank=True, null=True),
        ),
    ]
