# Generated by Django 2.1.7 on 2020-09-28 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_auto_20200910_0158'),
        ('borrowers', '0019_auto_20200928_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country1',
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addressCountry', to='settings.Country'),
        ),
    ]
