# Generated by Django 2.1.7 on 2020-10-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0020_auto_20200928_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
