# Generated by Django 2.1.7 on 2020-10-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0022_auto_20201006_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='clientSince',
        ),
    ]
