# Generated by Django 2.1.7 on 2020-10-06 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0024_borrower_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='branchCode',
        ),
    ]
