# Generated by Django 2.1.7 on 2020-10-25 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0025_remove_borrower_branchcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addressType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addressAddressType', to='settings.AddressType'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contactType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactContactType', to='settings.ContactType'),
        ),
        migrations.AlterField(
            model_name='identification',
            name='identificationType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identificationIdentificationType', to='settings.IdentificationType'),
        ),
    ]
