# Generated by Django 2.1.7 on 2020-10-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0026_auto_20201026_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='bookValue',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='fullyPaidPercent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='fullyPaidSharesNo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='initialPaidUpShare',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='grossIncome',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='monthlyExpenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='netTaxableIncome',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='grossIncome',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
