# Generated by Django 2.1.7 on 2020-12-01 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0028_auto_20201201_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowerCommittee', to='committees.Committee'),
        ),
    ]
