# Generated by Django 2.1.7 on 2020-08-02 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('committees', '0008_auto_20200730_0614'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_type', models.CharField(blank=True, max_length=255, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('isViewed', models.BooleanField(default=False)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='committees.Committee')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_content_type', to='contenttypes.ContentType')),
            ],
        ),
    ]
