# Generated by Django 2.1.7 on 2020-08-02 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationview_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationview',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewedNotifcations', to='committees.Committee'),
        ),
        migrations.AlterField(
            model_name='notificationview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewedNotifcations', to=settings.AUTH_USER_MODEL),
        ),
    ]
